---
sidebar: sidebar
permalink: rn/whats_new.html
keywords:
summary:
---

= What's new with the Astra REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Astra REST API to bring you new features, enhancements, and bug fixes.

== 5 August 2021

This release includes bug fixes and a major expansion of the Astra REST API.

=== Introduction of the Astra Control Center deployment model

In addition to the Astra Control Service offering provided as a public cloud service, this release also includes the Astra Control Center on-premises deployment model. You can install the Control Center offering at your site to manage your local Kubernetes environment. The two deployment models share the same REST API, with minor differences as noted in the documentation.

=== Expansion of the primary REST resources

The number of resources accessible through the Astra REST has greatly expanded, with many of the new resources providing a foundation for the on-premises Astra Control Center offering. The new resources include: ASUP, entitlement, feature, license, setting, subscription, bucket, cloud, cluster, managed cluster, storage backend, and storage class. See link:../endpoints/resources.html[Resources] for more information.

=== Additional endpoints supporting an Astra deployment

In addition to the expanded primary Astra resources, there are several other new endpoints available to support an Astra deployment.

OpenAPI support::
The OpenAPI endpoints provide access to the current OpenAPI JSON document and other related resources.

OpenMetrics support::
The OpenMetrics endpoints provide access to the account metrics through the OpenMetrics resource. Support is available with the Astra Control Center deployment model.

== 15 April 2021

This release includes the following new features and enhancements.

=== Introduction of the REST API

The Astra REST API is now available for use with the Astra Control Service. It was created based on REST technologies and current best practices. The API provides a foundation for the automation of your Astra deployments and includes the following features and benefits.

Resources::
There are fourteen REST resources available.

API token access::
Access to the REST API is provided through an API access token which you can generate through the web user interface.

Support for collections::
There is a rich set of query parameters which can be used to access the resources collections. Some of the supported operations include filtering, sorting, and pagination.
