---
sidebar: sidebar
permalink: workflows_infra/workflows_infra_before.html
keywords:
summary:
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The common Astra workflows can be used with both Astra Control deployment models.

== General preparation

xxx

Before using any of the Astra REST API workflows, make sure to review link:../get-started/prepare_to_use_workflows.html[Prepare to use the workflows].

== Workflow categories

The workflows are organized in different categories to make it easier to locate the one you want.

=== Storage backends

xxx

>> These workflows allow you to manage users and identity, including credentials, roles, and tokens.

>>>>>>>>>>>>>>

When storage classes are listed for unmanaged clusters, additional NetApp-provided storage classes are added to the collection. These are indicated by the resource "available" key having the value of "Eligible".

When storage classes are listed for managed clusters, only the actual storage classes available to the cluster are included in the collection.
