---
sidebar: sidebar
permalink: workflows_infra/workflows_infra_before.html
keywords:
summary:
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use these workflows to create and maintain the infrastructure used with the Astra Control Center deployment model. In most case, the workflows can also be used with Astra Control Service.

== General preparation

Before using any of the Astra workflows, make sure to review link:../get-started/prepare_to_use_workflows.html[Prepare to use the workflows].

== Workflow categories

The workflows are organized in different categories to make it easier to locate the one you want.

=== Identity and access

These workflows allow you to manage identity and how Astra is accessed. Workflows using the following resources are available:

* Users
* Credentials
* Tokens

=== Buckets

xxx
>> S3

=== Storage backends

xxx


When storage classes are listed for unmanaged clusters, additional NetApp-provided storage classes are added to the collection. These are indicated by the resource "available" key having the value of "Eligible".

When storage classes are listed for managed clusters, only the actual storage classes available to the cluster are included in the collection.

=== Clusters

xxx
