---
sidebar: sidebar
permalink: intro/introduction.html
keywords: introduction, Astra REST API
summary:
---

= Introduction to the Astra REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Most customers initially access the NetApp Astra service using a web browser. However, the service also includes a REST API which you can access directly using a programming language or utility such as Curl. The major highlights and benefits of the API are presented below.

[NOTE]
In addition to accessing the REST API directly, you can use other automation technologies that are based on the REST API. Ansible is very popular.

==== Built on REST technology and design principles

The Astra API has been designed using REST technology and current best practices. The core technology includes:

* Hypertext Transfer Protocol (HTTP)
* JavaScript Object Notation (JSON)
* Problem Details for HTTP APIs
* Transport Layer Security (TLS)

==== Clear mapping between REST endpoint resources and object model

The external REST endpoints used to access the resources map to a consistent object model maintained internally by the Astra service. The object model is described using UML and helps to clearly define the API actions and results.

==== Access to the NetApp cloud token-based security

To use the REST API, you first need to access the Astra web user interface. Sign in to the service is managed using the OAuth2 standard as provided by Auth0.com.

==== Rich set of query parameters

The REST API provides a rich set of query parameters that can be used to access the resources, especially collections. Some of the supported operations include:

* Filtering
* Sorting
* Pagination
* Count

==== Alignment with the Astra web UI

The Astra web interface uses the same REST API and so there is consistency between the two access paths and the user experience.

==== Robust debugging and problem determination data

The Astra REST API provides a robust debugging and problem determination capability, including events and notifications.
