---
sidebar: sidebar
permalink: intro/introduction.html
keywords: introduction, Astra REST API
summary:
---

= Introduction to the Astra REST API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Customers initially access the NetApp Astra service using a web browser. However, Astra also includes a REST API that you can use with a programming language or utility such as Curl. The major highlights and benefits of the API are presented below.

// Add workflow section

[NOTE]
In addition to accessing the REST API directly, you can use other automation technologies that are based on the REST API.

==== Built on REST technology

The Astra API has been created using REST technology and current best practices. The core technology includes HTTP, JSON, and RBAC.

==== Clear mapping between REST endpoint resources and object model

The external REST endpoints used to access the resources map to a consistent object model maintained internally by the Astra service. The object model is designed using entity relationship (ER) modeling and helps to clearly define the API actions and responses.

==== Rich set of query parameters

The REST API provides a rich set of query parameters that can be used to access the resources collections. Some of the supported operations include:

* Filtering
* Sorting
* Pagination

==== Alignment with the Astra web UI

The Astra web interface uses the same REST API and so there is consistency between the two access paths and the user experience.

==== Robust debugging and problem determination data

The Astra REST API provides a robust debugging and problem determination capability. This includes events and notifications generated internally as well as support for the Problem Details for HTTP APIs standard.
