---
sidebar: sidebar
permalink: rest-core/basic_operation.html
keywords: concepts
summary:
---

= Basic operational characteristics
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
xxx

>> Guiding Astra REST API, see "API conventions"
>> OA / basic operational characteristics
>> remove overlapping content at bottom

=== Resource types and schemas

xxx
>> metadata (list? table?)
>> First 3-4 variables always included (list? table?)

=== Resource instances and identifiers

xxx
>> UUIDv4
>> see "object references and access" (OA)

=== Collections of resource instances

xxx

=== HTTP messages

xxx
* HTTP methods
* Request and response headers
* Etc

See link:http_details.html[HTTP details] for more information.

=== URI endpoints

xxx
>> OTS, mention URL and link to topic

[NOTE]
The URL format used to access the Astra REST API is tightly coupled with the underlying object model. See link:url_format.html[URL format for API access] for more information.

=== JSON formatting

xxx
>> request body and response body
>> table with various types? See API conventions

=== Versioning considerations

xxx
