---
sidebar: sidebar
permalink: rest-core/resources_collections.html
keywords: concepts
summary:
---

= Resources and collections
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Astra REST API provides access to resource instances and collections of resource instances. These resources provide the foundation for the actions available with the API.

[NOTE]
Conceptually a REST *resource* is similar to an *object* used with object-oriented programming (OOP) languages and systems. Sometimes these terms can be used interchangeably depending on the context. But in generally, the term "resource" is preferred when referring to the external API actions while "object" is used when the data is stored internally at the server.

== Attributes of an Astra resources

The Astra resource APIs conform to RESTful design principles. Each Astra resource instance is created based on a resource type. A set of resource instances is known as a collection. All API calls act on an individual resource or a collection of resources.

===== Resource types

The resource types included with the Astra REST API have the following characteristics:

* Every resource type is defined using a schema (typically in JSON)
* Every resource schema includes the resource type and version

===== Resource instances

Resource instances available through the Astra REST API have the following characteristics:

* Created based on a resource type as indicated by a *mimetype* value
* Composed of stateful data which is maintained by the Astra service
* Accessible through a unique and long-lived URL
* Has one or more representations in JSON which is appended to the mimetype

===== Resource instances

Resource collections available through the Astra REST API have the following characteristics:

* The set of resource instances of a specific resource type is known as a collection
* Collections of resource instances have a unique and long-lived URL

===== Instance identifiers

Every REST resource instance is assigned a unique identifier when it is created. This identifier a 128-bit UUIDv4 value. The assigned UUID values are globally unique and immutable. After issuing an API call that creates a new object instance, a URL with the associated id value is returned to the caller in the location header of the HTTP response. You can extract the identifier and use it on subsequent calls when referring to the resource instance.

== Common type definition for Astra resources

Each Astra resource is defined using a common format.

===== Common data

Every API resource has the common key-values shown in the following table.

[cols="15,85"*,options="header"]
|===
|Key
|Description

|type
|Every resource shall have a globally unique resource type contained in the value of the "type" key. This shall be known as the "resource type".

|version
|Every resource shall have a version identifier contained in the value of the "version" key. This shall be known as the "resource version".

|id
|Every resource shall have a globally unique identifier contained in the value of the "id" key. This shall be known as the "resource identifier". The resource identifier shall act as the primary key for collections.

|metadata
|Every resource shall have a metadata object. The metadata object contains user and system labels.
|===

===== Metadata object

Each Astra resource includes a metadata JSON object with the key-values shown in the following table. The key value is `metadata`.

[cols="15,85"*,options="header"]
|===
|Key
|Description

|labels
|JSON Array of client-specified labels associated with the resource.

|creationTimestamp
|JSON string containing a timestamp indicating when the resource was created.

|modificationTimestamp
|JSON String containing an ISO-8601 formatted timestamp indicating when the resource was last altered.

|createdBy
|JSON String containing a UUIDv4 identifier of the User ID that created the resource. If the resource was created by an internal system component, and there is no UUID associated with the creating entity, the NULL UUID shall be used.

|===

===== Resource state

Selected resource types have a state value which can be used to control access and orchestrate orderly lifecycle transitions.

== Summary of resources for the Astra REST API

The resource endpoints provided in the Astra REST API are organized into three categories including:

* Core
* Managed applications
* Topology

The resources are listed below. See link:../endpoints/resource_apis.html[Resource APIs] for more informaiton.

===== Core resources

The core resource endpoints provide foundational services needed to establish and maintain the Astra runtime environment. The endpoints include:

* Credential
* Event
* Notification
* Role Binding
* Token
* Unread notification
* User

===== Managed application resources

The managed application resource endpoints provide access to the managed Kubernetes applications. The endpoints include:

* Application asset
* Application backup
* Application snapshot
* Managed app
* Schedule

===== Topology resources

The topology resource endpoints provide access to the unmanaged applications and storage resources. The endpoints include:

* App
* Volume
