---
sidebar: sidebar
permalink: rest-core/url_format.html
keywords:
summary:
---

= URL format
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The format of the URL used to access a resource or collection is a composite value.

== Format of the URL

The general structure of the URL with an example is presented below.

===== Account as the root

The root of the resource path to every REST endpoint is the Astra account. And so all paths in the URL begin with `/account/{account_id}` where `account_id` is the unique UUIDv4 value. Internally this reflects a design where all resource access is based on a specific account.

===== Endpoint resource category

The Astra resource endpoints fall into three different categories:

* Core
* Managed application
* Topology

See link:resources_collections.html[Resources and collections] for more information.

===== Category version

Each of the three resource categories has a global version that controls the version of the resources accessed. Semantic versioning is used, and for example so a move from version 1 (v1) to version 2 (v2) will introduce breaking changes in the API.

[IMPORTANT]
I think it's a good idea to describe how versioning works, URL category version versus individual resource version. But the last time I spoke with David Slik, this area of the API was still undecided.

===== Resource instance or collection

A combination of resource and resource identifiers can be used, depending on if a resource instance or collection is accessed.

===== Example

* Resource path
+
Based on structure presented above, a typical path to an endpoint is: `/accounts/{account_id}/core/v1/users`.

* Complete URL
+
The full URL for the corresponding endpoint is: `https://astra.netapp.io/accounts/{account_id}/core/v1/users`.
