---
sidebar: sidebar
permalink: reference/api_reference.html
keywords:
summary:
---

= API reference
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can access the details of all the Astra REST API calls, including the HTTP methods, input parameters, and responses. This complete reference is helpful when developing automation applications using the REST API.

[NOTE]
The REST API reference documentation is currently available online with the Astra service.

.Before you begin

You need an account for the Astra service.

.Steps

. Sign in to the Astra service using your account credentials.
+
link:https://astra.netapp.io[https://astra.netapp.io^]

. Click the figure icon at the top right of the page and select *API access*.

. At the top of the page click the URL displayed under *API Documentation*.
//At the top of the page, copy the URL displayed under *API Documentation* and paste it into your browser.

. Provide your account credentials again if prompted.
