---
sidebar: sidebar
permalink: workflows/before_workflow_processes.html
keywords:
summary:
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should be familiar with the high-level organization and format of the Astra workflow processes before using them with a live deployment.

== Introduction

A _workflow_ is a sequence of one or more steps used to accomplish a specific administrative task or goal. With the Astra workflows, each step of an administrative workflows is one of the following:

* REST API call
* Invocation of another workflow

The workflows provided include the minimum steps and parameters needed to accomplish each task. You can use these workflows as a starting point and customize them for your environment as needed.

== Workflow types

Each of the Astra resource APIs provides access to a primary resource type available as either an instance or collection. The administrative workflows access and use these resources. Some of the workflows are small and apply to only a single resource type, while others workflows can be larger and involve many resource types or API operations. To accommodate these differences, there are different types of workflows as described in the table below.

[cols="20,80"*,options="header"]
|===
|Workflow type
|Description
|Basic
|These workflows use one resource type and typically consist of a single step. Given their small size, multiple workflows focused on a single resource can be collected together on one page.
|Complex
|Each of these workflows is larger and involves multiple resource types or steps. In this case, there is only one workflow on each page.
|===

== Common parameters and variables

There are several parameters or variables common among the workflows.

==== Authorization request header

All of the workflows require an API bearer token. You must include this in the API call using the `Authorization` request header. See link:../get-started/get+api_token.html[Getting an API access token] for more information. Rather than cite this header as a prerequisite in every REST API call, it is considered as a universal requirement.

==== Presentation of API tokens and other variables

Most of the variable tokens, identifiers, and other variables used in the sample REST API calls consist of long strings of letters, numbers, and special characters. They are considered opaque with no easily discernible content or meaning. Therefore, rather than include the actual original strings, smaller reserved keywords are used instead. This can have several benefits:

* The Curl and JSON samples are clearer and easier to understand.

* Because all keywords use the same format (including capital letters), you can quickly identify the location and content to insert or extract.

* No value is lost, because the original values could not be copied and used with an actual deployment.

There are two types of variables identifiers used in the workflow samples.

Path parameters::
These are variables used in the URL endpoint paths as defined in the API specification. For example, considered the following endpoint available in the User API: `/accounts/{account_id}/core/v1/users`. In this case, the `account_id` will be rendered as <ACCOUNT_ID> in a Curl sample. This same pattern applies to all the path parameters (such as, `user_id` and `app_id`).

Additional keywords::
There are additional keywords reserved for common variables as presented in the table below.

[cols="25,75"*,options="header"]
|===
|Keyword
|Description
|<API_TOKEN>
|This is a bearer token generated at the Astra web user interface which must be included with the HTTP `Authorization` request header in an API call.
|===

Here is an example using the two different types of keywords *<ACCOUNT_ID>* and *<API_TOKEN>*:

[source,curl]
curl --location --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/core/v1/users' --header 'Content-Type: application/json' --header 'Authorization: Bearer <API_TOKEN>'
