---
sidebar: sidebar
permalink: workflows/wf_app_cloning.html
keywords:
summary:
---

= Cloning and restoring an app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
These workflow describe how to clone and restore your managed applications.

==== Cloning an app

Here are a few things to consider when cloning an application. The parameters described are in the JSON input.

Source cluster identifier::
The value of `sourceClusterId` always identifies the cluster where the original app is installed.

Cluster identifier::
The value of `clusterId` identifies the cluster where the new app will be installed.

* When cloning within the same cluster, `clusterID` and `sourceClusterId` must have the same value.
* When cloning across clusters, `clusterId` must have the ID of the target cluster.

Namespaces::
When cloning an app, the `namespace` value must be different from the namespace of the original source app. Further, the namespace cannot exist and Astra will create it.

Backups and snapshots::
You can clone an application from either an existing backup or snapshot using the `backupId` or `snapshot` parameters respectively. If you don't provide either a backup or snapshot, Astra will create a backup of the application first and then clone from the backup.

==== Restoring an app

Restoring an application is very similar to the clone operation. The main difference when restoring an app is that you must have either a backup or snapshot.
