---
sidebar: sidebar
permalink: workflows/wf_app_cloning.html
keywords:
summary:
---

= Cloning and restoring an app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
These workflow describe how to clone and restore your managed applications.

=== Cloning an app

Here are a few things to consider when cloning an application. The parameters described below are part of the JSON input.

Source cluster identifier::
The value of `sourceClusterID` always identifies the cluster where the original app is installed.

Cluster identifier::
The value of `clusterID` identifies the cluster where the new app will be installed.

* When cloning within the same cluster, `clusterID` and `sourceClusterID` have the same value.
* When cloning across clusters, the two values are different and `clusterID` should be the ID of the target cluster.

Namespaces::
The `namespace` value must be different than the original source app. Further, the namespace for the clone cannot exist and Astra will create it.

Backups and snapshots::
You can optionally clone an application from an existing backup or snapshot using the `backupID` or `snapshotID` parameters. If you don't provide a backup or snapshot, Astra will create a backup of the application first and then clone from the backup.

=== Restoring an app

Here are a few things to consider when restoring an application.

* Restoring an application is very similar to the clone operation.
* When restoring an app, you must provide either a backup or snapshot.
