---
sidebar: sidebar
permalink: workflows/wf_create_backup.html
keywords:
summary:
---

= Create a backup for a managed app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a backup for a specific managed application. You can use the backup to restore or clone the app.

=== Before you begin

You must have the ID of the managed app you want to create a backup for. If needed you can use the workflow link:wf_list_man_apps.html[List the managed apps] to locate the application.

=== 1. Create a backup

Perform the following REST API call.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|POST
|/accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}/appBackups
|===

===== Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|managed app id
|Path
|Yes
|Identifies the managed application where the backup will be created.
|JSON
|Body
|Yes
|Provides the parameters for the backup. See the example below.
|===

===== JSON input example
[source,json]
{
  "type": "application/astra-appBackup",
  "version": "1.0",
  "name": "backup-david-1"
}

===== Curl example: Create a backup for the app
[source,curl]
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>/appBackups' --header 'Content-Type: application/astra-appBackup+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --d @JSONinput
