---
sidebar: sidebar
permalink: workflows/wf_delete_failed_app.html
keywords:
summary:
---

= Delete a failed app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You might be unable to remove a managed app if it has a backup or snapshot in a failed state. In this case you can manually remove the app using the workflow described below.

=== 1. Select the managed app to delete

Perform the workflow link:wf_list_man_apps.html[List the managed apps] and select application you want to remove.

=== 2. List the existing backups for the app

Perform the workflow link:wf_list_backups.html[List the backups].

=== 3. Delete all the backups

Delete all the app backups by performing the workflow link:wf_delete_backup.html[Delete a backup] for each backup in the list.

=== 4. List the existing snapshots for the app

Perform the workflow link:wf_list_snapshots.html[List the snapshots].

=== 5. Delete all the snapshots

Perform the workflow link:wf_delete_snapshot.html[Delete a snapshot] from each snapshot in the list.

=== 6. Remove the application

Perform the workflow link:wf_unmanage_app.html[Unmanage an app] to remove the application.
