---
sidebar: sidebar
permalink: workflows/wf_get_man_app.html
keywords:
summary:
---

= Get a managed app
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can retrieve all the resource variables describing a single managed application.

=== Before you begin

You must have the ID of the managed app you want to retrieve. If needed you can use the workflow link:wf_list_man_apps.html[List the managed apps] to locate the application.

=== 1. Get the application

Perform the following REST API call.

[cols="25,75"*,options="header"]
|===
|HTTP method
|Path
|GET
|/accounts/{account_id}/k8s/v1/managedApps/{managedApp_id}
|===

===== Additional input parameters

In addition to the parameters common with all REST API calls, the following parameters are also used in the curl examples for this step.

[cols="25,10,10,55"*,options="header"]
|===
|Parameter
|Type
|Required
|Description
|managed app id
|Path
|Yes
|ID value of the managed application to retrieve.
|===

===== Curl example: Return all data for the application
[source,curl]
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/managedApps/<MANAGED_APP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
