---
sidebar: sidebar
permalink: endpoints/ep_user.html
keywords:
summary:
---

= User API
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The User API allows you to access and administer the Astra users.

== Endpoints

The endpoints included with this API are shown in the table below.

[cols="25,75"*,options="header"]
|===
|Type
|Endpoint
|Collection
|/accounts/{account_id}/core/v1/users
|Instance
|/accounts/{account_id}/core/v1/users/{user_id}
|===

== Resource definition

==== Media type

The following media types are supported:

* application/astra-user
* application/astra-user+json

==== State

The User resource type maintains a state which can be one of the values in the table below.

[cols="20,80"*,options="header"]
|===
|State
|Description
|pending
|The user account is in the process of being created. The API caller can read and modify the user resource. This is the default value.
|active
|The user account is operational. The user can log in if account `isEnabled` is `true`.
|suspended
|The user account is suspended and cannot be used regardless of account `isEnabled` setting.
|===

==== Resource example

[source,json]
{
    "type" :  "application/astra-user",
    "version" : "1.0",
    "id" : "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa",
    "state" : "active",
    "isEnabled" : "true",
    "authID" : "HteLK3hk28sdbDLKHReB",
    "authProvider" : "cloud-central",
    "firstName" : "John",
    "lastName" : "Doe",
    "companyName" : "NetApp, Inc.",
    "email" : "jdoe@example.com",
    "phone" : "408-555-22222",
    "postalAddress" : {
         "addressCountry" : "US",
         "addressLocality" : "Sunnyvale",
         "addressRegion" : "California",
         "postalCode" : "94089",
         "streetAddress1" : "495 East Java Drive"
    },
    "sendWelcomeEmail" : "true",
    "enableTimestamp" : "2020-08-05T14:24:54.128427Z",
    "lastActTimestamp" : "2020-08-05T14:24:54.128427Z",
    "metadata" : {
        "labels" : [  ],
        "creationTimestamp" : "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp" : "2020-08-06T12:24:52.256624Z",
        "createdBy" : "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
    }
}

== API operations

The operations available with this API can be defined in terms of the HTTP headers and methods.

==== HTTP headers

The following headers are used with this API.

[cols="30,15,55"*,options="header"]
|===
|Header
|Type
|Description
|Authorization
|Request
|Bearer token of the user or API key for the user.
|Location
|Response
|Full URL of the newly created resource.
|===

==== Summary of API calls

A summary of the API calls available with this API is shown in the table below.

[cols="15,10,25,50"*,options="header"]
|===
|Action
|HTTP
|Path
|Description
|Create user
|POST
|/core/v1/users
|Create a new user based on the contents of the request body.
|List users
|GET
|/core/v1/users
|Returns an array of JSON objects for the user resources based on the query parameters.
|Read user
|GET
|/core/v1/users/{user_id}
|Returns a JSON object for the user resource based on the user id.
|Replace user
|PUT
|/core/v1/users/{user_id}
|Updates the entire resource with the supplied JSON request body. Key values that are not user modifiable are preserved.
|Delete user
|DELETE
|/core/v1/users/{user_id}
|Removes the stored user resource.
|===
