---
sidebar: sidebar
permalink: endpoints/resources.html
keywords:
summary:
---

= Resources and endpoints
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the resources provided through REST API to automate an Astra deployment. Each resource is access through one or more endpoints. This section provides an introduction to the REST resources which is useful as part of planning an automation deployment.

[NOTE]
The format of the path and full URL used to access the Astra resources is based on several values. See link:../rest-core/url_format.html[URL format] for more information. Also see link:../reference/api_reference.html[API reference] for details about using the Astra resources.

== Primary Astra resources and endpoints

The primary resource endpoints provided in the Astra REST API are organized in three categories. The Astra release when the resource first became available is indicated for each.

=== Core resources

The core resource endpoints provide the foundational services needed to establish and maintain the Astra runtime environment.

ASUP::
The ASUP resources represent the AutoSupport bundles used by NetApp support.

Credential::
The credential resources contain security related information which can be used with Astra users, clusters, buckets, and storage backends.

Entitlement::
The entitlement resources represent the features and capacities available for an account based on the active licenses and subscriptions.

Event::
The event resources represent all the events occurring in the system, including the subset classified as notifications.

Feature::
(Q2) xxx

License::
(Q2) xxx

Notification::
xxx

Role Binding::
xxx

Setting::
(Q2) xxx

Subscription::
(Q2) xxx

Token::
xxx

Unread notification::
xxx

User::
xxx

=== Managed application resources

The managed application resource endpoints provide access to the managed Kubernetes applications.

Application asset::
xxx

Application backup::
xxx

Application snapshot::
xxx

Managed application::
xxx

Schedule::
xxx

=== Topology resources

The topology resource endpoints provide access to the unmanaged applications and storage resources.

App::
xxx

Bucket::
(Q2) xxx

Cloud::
(Q2) xxx

Cluster::
(Q2) xxx

Managed cluster::
(Q2) xxx

Storage backend::
(Q2) xxx

Storage class::
(Q2) xxx

Volume::
xxx

== Additional resources and endpoints

There are several additional resources and endpoints that you can use to support an Astra deployment.

=== OpenAPI

xxx

=== OpenMetrics

xxx
