---
sidebar: sidebar
permalink: endpoints/resources.html
keywords:
summary:
---

= Resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the resources provided through REST API to automate the administration of an Astra deployment. Each resource is access through one or more endpoints. This section provides an introduction to these resources which is useful as part of planning an automation deployment.

See the following for more information:

* link:../reference/api_reference.html[API reference]
+
This page provides access to a more complete description of the Astra REST API which you can use when developing your automation applications.

* link:../workflows/workflows.html[Administrative workflows]
+
This section includes practical examples of making API calls to perform common administrative tasks.

=== Summary of the Astra resources

* App
* Application asset
* Application backup
* Application snapshot
* Credential
* Event
* Managed application
* Notification
* Role binding
* Schedule
* Token
* Unread notification
* User
* Volume
