---
sidebar: sidebar
permalink: endpoints/resource_apis.html
keywords:
summary:
---

= Resource APIs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Astra REST API is composed of several smaller APIs, each providing access to a specific resource type through one or more REST endpoints. This section provides a concise description of these APIs, which is useful as part of planning an Astra automation deployment.

==== Consistent format

Each of the resource APIs is described in a consistent format. The following information is provided for each API:

* List of REST endpoints
* Overview of the resource definition
* Summary of the available API operations

Note that the *Path* variable provided for each of the API operations is abbreviated by removing the `/accounts/{account_id}` prefix. You must include this in the full URL path when issuing an actual API call.

==== Additional information

* link:../reference/api_reference.html[API reference]
+
This page provides access to a more complete description of the Astra REST API which you can use when developing your automation applications.

* link:../workflows/workflows.html[Administrative workflows]
+
This section includes practical examples of making API calls to perform common administrative tasks.
