---
sidebar: sidebar
permalink: endpoints/resources.html
keywords:
summary:
---

= Resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the resources provided through REST API to automate the administration of an Astra deployment. Each resource is access through one or more endpoints. This section provides an introduction to these resources which is useful as part of planning an automation deployment.

See link:../reference/api_reference.html[API reference] for more information.

== Summary of resources for the Astra REST API

The resource endpoints provided in the Astra REST API are organized in three categories.

===== Core resources

The core resource endpoints provide the foundational services needed to establish and maintain the Astra runtime environment. The endpoints include:

* ASUP *(Q2)*
* Credential
* Entitlement *(Q2)*
* Event
* Feature *(Q2)*
* License *(Q2)*
* Notification
* Role Binding
* Setting *(Q2)*
* Subscription *(Q2)*
* Token
* Unread notification
* User

===== Managed application resources

The managed application resource endpoints provide access to the managed Kubernetes applications. The endpoints include:

Application asset::
xxx

Application backup::
xxx

Application snapshot::
xxx

Managed application::
xxx

Schedule::
xxx

===== Topology resources

The topology resource endpoints provide access to the unmanaged applications and storage resources. The endpoints include:

* App
* Bucket *(Q2)*
* Cloud *(Q2)*
* Cluster *(Q2)*
* Managed cluster *(Q2)*
* Storage backend *(Q2)*
* Storage class *(Q2)*
* Volume

== Format of the access path and URL

The format of the path and full URL used to access the Astra resources is based on several values. See link:../rest-core/url_format.html[URL format] for more information.
