---
sidebar: sidebar
permalink: endpoints/resources.html
keywords:
summary:
---

= Resources and endpoints
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the resources provided through REST API to automate an Astra deployment. Each resource is access through one or more endpoints. This section provides an introduction to the REST resources which is useful as part of planning an automation deployment.

[IMPORTANT]
DP: Review the text at the Swagger page for each of the resources.

[NOTE]
The format of the path and full URL used to access the Astra resources is based on several values. See link:../rest-core/url_format.html[URL format] for more information. Also see link:../reference/api_reference.html[API reference] for details about using the Astra resources.

== Primary Astra resources and endpoints

The primary resource endpoints provided in the Astra REST API are organized in three categories. The Astra release when the resource first became available is indicated for each.

[NOTE]
Each resource can be accessed with the full set of CRUD operations (create, read, update, delete) except where noted.

=== Core resources

The core resource endpoints provide the foundational services needed to establish and maintain the Astra runtime environment.

ASUP::
The ASUP resources represent the AutoSupport bundles used by NetApp support.

Credential::
The credential resources contain security related information which can be used with Astra users, clusters, buckets, and storage backends.

Entitlement::
The entitlement resources represent the features and capacities available for an account based on the active licenses and subscriptions.

Event::
The event resources represent all the events occurring in the system, including the subset classified as notifications.

Feature::
The feature resources represent selected Astra features which you can query to determine if they are enabled or disabled in the system. Access is limited to read-only.

License::
The license resources represent the licenses available with an Astra account.

Notification::
The notification resources represent Astra events that have a notification destination. Access is provided on a per-user basis.

Role Binding::
The role binding resources represent the relationships between specific pairs of users and accounts. In addition to the linkage between the two, a set of permissions is specified for each through a specific role.

Setting::
The setting resources represent a collection of key-value pairs which describe a feature for a specific Astra account.

Subscription::
The subscription resources represent the active subscriptions for the Astra account.

Token::
The token resources represent the tokens used to programmatically access the Astra REST API.

Unread notification::
The unread notification resources represent notifications assigned to a specific user but not yet read.

User::
The user resources represent Astra users able to access the system based on their associated role.

=== Managed application resources

The managed application resource endpoints provide access to the managed Kubernetes applications.

Application asset::
The application asset resources represent internal collections of state information needed to manage the Astra applications.

Application backup::
The application backup resources represent backups of the managed applications.

Application snapshot::
The application backup resources represent snapshots of the managed applications.

Managed application::
The managed app resources represent Kubernetes applications that are managed by Astra.

Schedule::
The schedule resources represent data protection operations that are scheduled for the managed applications.

=== Topology resources

The topology resource endpoints provide access to the unmanaged applications and storage resources.

App::
xxx

Bucket::
(Q2) xxx

Cloud::
(Q2) xxx

Cluster::
(Q2) xxx

Managed cluster::
(Q2) xxx

Storage backend::
(Q2) xxx

Storage class::
(Q2) xxx

Volume::
xxx

== Additional resources and endpoints

There are several additional resources and endpoints that you can use to support an Astra deployment.

[NOTE]
These resources and endpoints are not included in the Astra API reference documentation.

=== OpenAPI

xxx

=== OpenMetrics

xxx
