---
sidebar: sidebar
permalink: endpoints/resources.html
keywords:
summary:
---

= Resources and endpoints
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the resources provided through REST API to automate the administration of an Astra deployment. Each resource is access through one or more endpoints. This section provides an introduction to these resources which is useful as part of planning an automation deployment.

[NOTE]
The format of the path and full URL used to access the Astra resources is based on several values. See link:../rest-core/url_format.html[URL format] for more information. Also see link:../reference/api_reference.html[API reference] for more details about the Astra resources.

== Primary Astra resources and endpoints

The primary resource endpoints provided in the Astra REST API are organized in three categories.

==== Core resources

The core resource endpoints provide the foundational services needed to establish and maintain the Astra runtime environment. The endpoints include:

ASUP::
(Q2) xxx

Credential::
xxx

Entitlement::
(Q2) xxx

Event::
xxx

Feature::
(Q2) xxx

License::
(Q2) xxx

Notification::
xxx

Role Binding::
xxx

Setting::
(Q2) xxx

Subscription::
(Q2) xxx

Token::
xxx

Unread notification::
xxx

User::
xxx

==== Managed application resources

The managed application resource endpoints provide access to the managed Kubernetes applications. The endpoints include:

Application asset::
xxx

Application backup::
xxx

Application snapshot::
xxx

Managed application::
xxx

Schedule::
xxx

==== Topology resources

The topology resource endpoints provide access to the unmanaged applications and storage resources. The endpoints include:

App::
xxx

Bucket::
(Q2) xxx

Cloud::
(Q2) xxx

Cluster::
(Q2) xxx

Managed cluster::
(Q2) xxx

Storage backend::
(Q2) xxx

Storage class::
(Q2) xxx

Volume::
xxx

== Additional Astra resources and endpoints

There are several additional resources and endpoints that you can use to support an Astra deployment.

==== OpenAPI

xxx

==== OpenMetrics

xxx
