---
sidebar: sidebar
permalink: get-started/before_get_started.html
keywords:
summary:
---

= Before you begin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
There are several steps you should take to prepare to use the Astra REST API.

===== Review REST concepts and implementation

Make sure to review link:../rest-core/rest_implementation.html[Core REST implementation] for information about REST concepts and the details regarding how the Astra REST API is designed.

===== Review the User resource API

Take a quick look at the resource APIs and in particular the link:../endpoints/ep_user.html[User API] which is used in the *Hello world* Curl example.

===== Have Cloud Central account credentials
You'll need the *Auth0* account credentials to generate an API token which is needed to access the REST API.

===== Getting more information

You should be aware of the additional information resources as suggested in link:../information/additional_resources.html[Additional resources].
