---
sidebar: sidebar
permalink: get-started/get_api_token.html
keywords:
summary:
---

= Getting an API access token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can generate an authorization token at the Astra web interface to access the REST API.

[NOTE]
Astra API tokens never expire, however you can revoke a token if needed.

.Before you begin

You need an account for the Astra service.

.About this task

This task generates an API token that you can use with your calls to the Astra REST API. You should also retrieve the account ID.

.Steps

. Sign in to the Astra service using your account credentials.
+
https://astra.netapp.io/[https://astra.netapp.io^]

. Click the figure icon at the top right of the page and select *API access*.

. Click *Generate API token* on the page and in the popup window click *Generate API token*.

. Click the icon to copy the token string to the clipboard and save it in your editor.

.After you finish

When you access the Astra REST API through Curl or a programming language, you must include in the API bearer token in the `Authorization` request header. To revoke the token, see link:../additional/security.html[Security].
