---
sidebar: sidebar
permalink: get-started/get_api_token.html
keywords:
summary:
---

= Getting an API access token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can generate an authorization token at the Astra web interface to access the REST API.

[NOTE]
Astra API tokens never expire, however you can revoke a token if needed.

.Before you begin

You need an account for the Astra service.

.About this task

This task generates an API token a text string which xxx

You should also retrieve the account ID fields xxx (update steps)

.Steps

. Sign in to the Astra service using your account credentials.
+
https://astra.netapp.io/[https://astra.netapp.io^]

. Click the figure icon at the top right of the page and select *API access*.

. Click *Generate API token* on the page and in the popup window click *Generate API token*.

. Click the icon to copy the token string to the clipboard and save it in your editor.

.After you finish

You will need the to access the Astra API through Curl or another programming language. It must be included in the `Authorization` bearer token with each API request.
